### ISSUE TITLE
widgets.istex.fr is not up to date ?

### ISSUE THREAD

**Issue by kerphi** [istex/istex-widgets-angular#12]
Il semblerait que ni http://widgets.istex.fr ni  http://istex.github.io/ ne sont à jour par rapport aux dernières version des widgets. C'est normal ou un oubli ?

**Comment by thomasfrantz** [comment]
J'ai pas fait de cron qui met à jour automatiquement istex.github.io si c'est la question.
Et avant de mettre à jour, je voulais encore faire quelques tests :)

**Comment by niederlec** [comment]
De son côté, widgets.istex.fr est à jour, sur la branche master.

Un git pull est exécuté périodiquement.

Claude

**Comment by kerphi** [comment]
@thomasfrantz tu penses pouvoir mettre à jour istex.github.io prochainement ? (la cron coté widgets.istex.fr fera le reste automatiquement)

**Comment by thomasfrantz** [comment]
Oups :/
C'est bon, istex.github.io est à jour

**Comment by kerphi** [comment]
Merci Thomas

Le jeu. 13 oct. 2016 09:28, thomasfrantz notifications@github.com a
écrit :
