### ISSUE TITLE
Mise à jour API v4 vers API v5

### ISSUE THREAD

**Issue by kerphi** [istex/istex-widgets-angular#16]
Les widgets nécessiteront très probablement une mise à jour pour pouvoir fonctionner avec l'API v5 de la plateforme ISTEX. cf http://blog.istex.fr/a-venir-dans-la-version-5-de-lapi/

Le 1er juin sear la date de la bascule cf http://blog.istex.fr/version-5-de-lapi-deroulement-des-operations/
Les adaptations peuvent être dès aujourd'hui testée ici  https://api-v5.istex.fr

J'ai eu une remontée d'un utilisateur qui a testé les widgets actuels avec la v5 et il semblerait que les facettes nécessitent des ajustements (j'ai pas testé de mon coté).

**Comment by thomasfrantz** [comment]
La seule différence majeure que je voyais c'était la limite de recherche avec le système de scroll qui est pas vraiment simlple pour les widgets.
Je sais pas trop comment implémenter ça, je suis tout ouï si tu as des idées.

Je vais faire des tests cet aprèm pour vérifier s'il y a des bugs :)

À savoir aussi qu'avec les congés qu'il me reste, je finis le 6 ou le 7 Juin (au lieu du 30 sur mon contrat)

**Comment by TineArconn** [comment]
Bonjour Thomas,
Je ne pense pas qu'il soit nécessaire ni souhaitable d'implémenter le système de scroll dans les widgets. Le scrolling est surtout utilisé pour la récupération de gros volume (harvester par exemple) et empêche de se balader librement dans les pages de résultats, ce qui ne convient pas pour l'usage d'un site web.

Pour les widgets, je préconise de garder le système de pagination classique, en sachant que les résultats affichés seront limités à 10000 documents au maximum dans la version 5. L'API renverra une erreur si la `size` et le `from` combinés dépassent ce chiffre pour information.
