### ISSUE TITLE
Les comptages des facettes ne semblent pas être recalculés une fois qu'une facettes est actionnée

### ISSUE THREAD

**Issue by kerphi** [istex/istex-widgets-angular#3]
J'ai identifié un comportement que je trouve étrange.

Exemple, on coche emerald:
![image](https://cloud.githubusercontent.com/assets/328244/13936405/ca8151c8-efbd-11e5-9394-f417db3b48ba.png)

Alors la facette langue indique toujours les même comptages, ex pour le Russe : 
![image](https://cloud.githubusercontent.com/assets/328244/13936427/f2450182-efbd-11e5-9982-69187cb8ef0c.png)

Alors qu'on s'attendrait à voir des zéro apparaître au niveau du comptage Russe.

**Comment by thomasfrantz** [comment]
Effectivement, la fonctionnalité n'est pas en place.
J'avais commencé à travailler dessus mais j'ai pensé que la priorité allait au module Drupal.
Je vais essayer de finir ça d'ici peu.

**Comment by thomasfrantz** [comment]
La fonctionnalité a été ajoutée, j'ai fais des tests et ça semble cohérent.
Je laisse ouvert, au cas où tu remarques quelque chose que j'ai pu oublier :)
