### ISSUE TITLE
Retirer les références au widget auth dans la doc et dans le code

### ISSUE THREAD

**Issue by kerphi** [istex/istex-widgets-angular#4]
Vu que la partie métadonnées est libre, plus besoin de ce widget, autant clarifier le message auprès des utilisateurs en retirant les références à cet ancien widget non ?

ex en intro de la doc :
![image](https://cloud.githubusercontent.com/assets/328244/13936542/99b6342c-efbe-11e5-9cb3-21c23e9de38c.png)

**Comment by thomasfrantz** [comment]
Effectivement, je pense qu'on peut le supprimer, merci pour le retour :)
