### ISSUE TITLE
Erreur angular avec l'exemple 2 sans slider

### ISSUE THREAD

**Issue by parmentf** [istex/istex-widgets-angular#5]
Quand on reprend le code source de l'exemple 2, mais en mettant en commentaire l'inclusion de `rzslider`, on obtient une erreur angular:

```
angular.js:38Uncaught Error: [$injector:modulerr] 
```

http://errors.angularjs.org/1.5.2/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20http%3A%2F%2Ferrors.angularjs.org%2F1.5.2%2F%24injector%2Fmodulerr%3Fp0%3DrzModule%26p1%3DError%253A%2520%255B%2524injector%253Anomod%255D%2520http%253A%252F%252Ferrors.angularjs.org%252F1.5.2%252F%2524injector%252Fnomod%253Fp0%253DrzModule%250A%2520%2520%2520%2520at%2520Error%2520(native)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A6%253A416%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A25%253A147%250A%2520%2520%2520%2520at%2520b%2520(http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A24%253A211)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A24%253A454%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A39%253A287%250A%2520%2520%2520%2520at%2520p%2520(http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A7%253A355)%250A%2520%2520%2520%2520at%2520g%2520(http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A39%253A135)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A39%253A304%250A%2520%2520%2520%2520at%2520p%2520(http%253A%252F%252Fistex.github.io%252Fbower_components%252Fangular%252Fangular.min.js%253A7%253A355)%0A%20%20%20%20at%20Error%20(native)%0A%20%20%20%20at%20http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A6%3A416%0A%20%20%20%20at%20http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A40%3A60%0A%20%20%20%20at%20p%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A39%3A135)%0A%20%20%20%20at%20http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A39%3A304%0A%20%20%20%20at%20p%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A7%3A355)%0A%20%20%20%20at%20g%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A39%3A135)%0A%20%20%20%20at%20db%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A43%3A164)%0A%20%20%20%20at%20c%20(http%3A%2F%2Fistex.github.io%2Fbower_components%2Fangular%2Fangular.min.js%3A20%3A463

(désolé pour la longueur de l'URL, c'est angular qui me l'a crachée)

En rétablissant l'inclusion de rzslider, tout se passe bien.

C'est surprenant parce que la documentation laisse penser que ce slider est optionnel (comme je ne sais pas à quoi il correspond, je me suis dit que j'allais essayer sans).

**Comment by thomasfrantz** [comment]
Bonjour,

vous avez tout à fait raison, si on utilise pas le slider, on est censé pouvoir ne pas inporter le fichier js.
Je vais essayer de reproduire l'erreur et corriger ça au plus vite :)

Pour info, rzslider est un petit fichier Javascript qui génère les sliders que vous pouvez voir dans l'exemple 1 à droite (les barres bleues).

**Comment by thomasfrantz** [comment]
Voilà, normalement c'est corrigé :)
