### ISSUE TITLE
TemplateUrl

### ISSUE THREAD

**Issue by rmeja** [istex/istex-widgets-angular#7]
J'ai créé une nouvelle branche templateUrl qui contient un peu de refactoring de code concernant la gestion des templates dans les différentes directives. A toi de voir si tu souhaites merger la branche templateurl avec le master. :wink:

**Comment by thomasfrantz** [comment]
Je viens de voir le pull request.
Il me semble qu'à l'époque j'avais fait le choix consciemment de ne pas utiliser templateUrl, mais c'était il y a un an, je ne me souviens plus trop.

Je regarde ça, je fais des tests et je te tiens au courant :)

**Comment by rmeja** [comment]
L'utilisation de templateUrl me semble plus facile pour manipuler le code HTML avec les outils associés (coloration syntaxique, snippet, linter ...). Après, je te balance ca directement à ma sortie d'Angular 1 et, apres tout, c'est à toi de juger de la plus-value que cela peut apporter. :wink:

**Comment by thomasfrantz** [comment]
Alors j'ai réussi à comprendre pourquoi j'avait pris la décision : 
on voulait un seul fichier JS à importer, or si on fait des templates, il faut les importer un à un, on peut pas tout minifier dans un seul fichier.
N'ayant pas de solution simple pour résoudre cette technicité, j'ai pris la décision d'utiliser des String :/

Si tu connais un moyen autour de ça je suis preneur !
(Pour un projet perso j'ai fait un petit script qui transformait les templates en String du coup on peut travailler avec des fichiers HTML mais ça rajoute une étape de build)
